services:
  - type: web
    name: your-app-name
    env: python
    build:
      environment: python
      pythonVersion: 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  # Replace with your app’s start command
