services:
  - type: web
    name: transformconf
    env: python
    build:
      environment: python
      pythonVersion: 3.11.9  # Explicitly pin 3.11.x here
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install numpy==1.24.4
      pip install -r requirements.txt
    startCommand: python app.py
