services:
  - type: web
    name: your-app-name
    env: python
    build:
      environment: python
      pythonVersion: 3.12
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python app.py
