services:
  - type: web
    name: transformconf
    env: python
    build:
      environment: python
      pythonVersion: 3.11
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
